import {defineApp,feature} from './domain-config.mjs';
export default defineApp({
  "id": "ai-franchise-royalty-ad-fund-audit",
  "engine": "recovery",
  "title": "Franchise Royalty & Ad Fund Audit",
  "shortTitle": "Franchise Revenue Assurance",
  "tagline": "Reconstruct gross sales, audit royalties, and protect brand fund economics",
  "industry": "Franchise Financial Compliance",
  "uiPort": 4561,
  "apiPort": 5561,
  "accent": "#9333ea",
  "currency": "USD",
  "primaryOutcome": "Underreported royalties and ad-fund contributions identified and collected",
  "valueNarrative": "Connect franchise agreements, POS sales, delivery platforms, bank deposits, tax returns, GL data, and remittances.",
  "calculation": {
    "actualKey": "reportedAmount",
    "expectedKey": "expectedAmount",
    "actualLabel": "Reported remittance",
    "expectedLabel": "Contract-expected remittance",
    "varianceLabel": "Potential franchise recovery",
    "direction": "expected-minus-actual",
    "finding": "Sales reconstruction and agreement rules indicate underreported royalty or advertising-fund obligations.",
    "actions": [
      "Reconcile POS, delivery, bank, tax, and GL sales",
      "Apply agreement definitions, exclusions, and rates",
      "Issue audit finding and supporting schedule",
      "Track franchisee response and collection"
    ]
  }
},[
feature("franchise-agreement-library","FRA01","Franchise agreement library","Reconcile franchise agreement library using franchise agreements, POS detail, aggregator sales, bank deposits, tax filings, GL data, exemptions, and remittances.","Produce a governed franchise agreement library decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["franchisee","Franchisee / Location","text","Harbor Foods #184"],["period","Royalty Period","text","2026-Q2"],["reportedAmount","Reported Royalty & Fund","currency",184000],["expectedAmount","Expected Royalty & Fund","currency",228500]],{amountField:"reportedAmount",subjects:["Quick-service restaurant","Fitness franchise","Home-services franchise","Hospitality franchise","Retail franchise"]}),
feature("location-and-ownership-registry","FRA02","Location and ownership registry","Reconcile location and ownership registry using franchise agreements, POS detail, aggregator sales, bank deposits, tax filings, GL data, exemptions, and remittances.","Produce a governed location and ownership registry decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["franchisee","Franchisee / Location","text","Harbor Foods #184"],["period","Royalty Period","text","2026-Q2"],["reportedAmount","Reported Royalty & Fund","currency",184000],["expectedAmount","Expected Royalty & Fund","currency",228500]],{amountField:"reportedAmount",subjects:["Quick-service restaurant","Fitness franchise","Home-services franchise","Hospitality franchise","Retail franchise"]}),
feature("pos-sales-ingestion","FRA03","POS sales ingestion","Reconcile pos sales ingestion using franchise agreements, POS detail, aggregator sales, bank deposits, tax filings, GL data, exemptions, and remittances.","Produce a governed pos sales ingestion decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["franchisee","Franchisee / Location","text","Harbor Foods #184"],["period","Royalty Period","text","2026-Q2"],["reportedAmount","Reported Royalty & Fund","currency",184000],["expectedAmount","Expected Royalty & Fund","currency",228500]],{amountField:"reportedAmount",subjects:["Quick-service restaurant","Fitness franchise","Home-services franchise","Hospitality franchise","Retail franchise"]}),
feature("delivery-platform-reconciliation","FRA04","Delivery-platform reconciliation","Reconcile delivery-platform reconciliation using franchise agreements, POS detail, aggregator sales, bank deposits, tax filings, GL data, exemptions, and remittances.","Produce a governed delivery-platform reconciliation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["franchisee","Franchisee / Location","text","Harbor Foods #184"],["period","Royalty Period","text","2026-Q2"],["reportedAmount","Reported Royalty & Fund","currency",184000],["expectedAmount","Expected Royalty & Fund","currency",228500]],{amountField:"reportedAmount",subjects:["Quick-service restaurant","Fitness franchise","Home-services franchise","Hospitality franchise","Retail franchise"]}),
feature("bank-deposit-reconciliation","FRA05","Bank deposit reconciliation","Reconcile bank deposit reconciliation using franchise agreements, POS detail, aggregator sales, bank deposits, tax filings, GL data, exemptions, and remittances.","Produce a governed bank deposit reconciliation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["franchisee","Franchisee / Location","text","Harbor Foods #184"],["period","Royalty Period","text","2026-Q2"],["reportedAmount","Reported Royalty & Fund","currency",184000],["expectedAmount","Expected Royalty & Fund","currency",228500]],{amountField:"reportedAmount",subjects:["Quick-service restaurant","Fitness franchise","Home-services franchise","Hospitality franchise","Retail franchise"]}),
feature("tax-return-comparison","FRA06","Tax-return comparison","Reconcile tax-return comparison using franchise agreements, POS detail, aggregator sales, bank deposits, tax filings, GL data, exemptions, and remittances.","Produce a governed tax-return comparison decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["franchisee","Franchisee / Location","text","Harbor Foods #184"],["period","Royalty Period","text","2026-Q2"],["reportedAmount","Reported Royalty & Fund","currency",184000],["expectedAmount","Expected Royalty & Fund","currency",228500]],{amountField:"reportedAmount",subjects:["Quick-service restaurant","Fitness franchise","Home-services franchise","Hospitality franchise","Retail franchise"]}),
feature("gross-sales-reconstruction","FRA07","Gross-sales reconstruction","Reconcile gross-sales reconstruction using franchise agreements, POS detail, aggregator sales, bank deposits, tax filings, GL data, exemptions, and remittances.","Produce a governed gross-sales reconstruction decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["franchisee","Franchisee / Location","text","Harbor Foods #184"],["period","Royalty Period","text","2026-Q2"],["reportedAmount","Reported Royalty & Fund","currency",184000],["expectedAmount","Expected Royalty & Fund","currency",228500]],{amountField:"reportedAmount",subjects:["Quick-service restaurant","Fitness franchise","Home-services franchise","Hospitality franchise","Retail franchise"]}),
feature("exclusion-and-discount-validation","FRA08","Exclusion and discount validation","Reconcile exclusion and discount validation using franchise agreements, POS detail, aggregator sales, bank deposits, tax filings, GL data, exemptions, and remittances.","Produce a governed exclusion and discount validation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["franchisee","Franchisee / Location","text","Harbor Foods #184"],["period","Royalty Period","text","2026-Q2"],["reportedAmount","Reported Royalty & Fund","currency",184000],["expectedAmount","Expected Royalty & Fund","currency",228500]],{amountField:"reportedAmount",subjects:["Quick-service restaurant","Fitness franchise","Home-services franchise","Hospitality franchise","Retail franchise"]}),
feature("royalty-recalculation","FRA09","Royalty recalculation","Reconcile royalty recalculation using franchise agreements, POS detail, aggregator sales, bank deposits, tax filings, GL data, exemptions, and remittances.","Produce a governed royalty recalculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["franchisee","Franchisee / Location","text","Harbor Foods #184"],["period","Royalty Period","text","2026-Q2"],["reportedAmount","Reported Royalty & Fund","currency",184000],["expectedAmount","Expected Royalty & Fund","currency",228500]],{amountField:"reportedAmount",subjects:["Quick-service restaurant","Fitness franchise","Home-services franchise","Hospitality franchise","Retail franchise"]}),
feature("advertising-fund-recalculation","FRA10","Advertising-fund recalculation","Reconcile advertising-fund recalculation using franchise agreements, POS detail, aggregator sales, bank deposits, tax filings, GL data, exemptions, and remittances.","Produce a governed advertising-fund recalculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["franchisee","Franchisee / Location","text","Harbor Foods #184"],["period","Royalty Period","text","2026-Q2"],["reportedAmount","Reported Royalty & Fund","currency",184000],["expectedAmount","Expected Royalty & Fund","currency",228500]],{amountField:"reportedAmount",subjects:["Quick-service restaurant","Fitness franchise","Home-services franchise","Hospitality franchise","Retail franchise"]}),
feature("late-fee-and-interest-calculation","FRA11","Late fee and interest calculation","Reconcile late fee and interest calculation using franchise agreements, POS detail, aggregator sales, bank deposits, tax filings, GL data, exemptions, and remittances.","Produce a governed late fee and interest calculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["franchisee","Franchisee / Location","text","Harbor Foods #184"],["period","Royalty Period","text","2026-Q2"],["reportedAmount","Reported Royalty & Fund","currency",184000],["expectedAmount","Expected Royalty & Fund","currency",228500]],{amountField:"reportedAmount",subjects:["Quick-service restaurant","Fitness franchise","Home-services franchise","Hospitality franchise","Retail franchise"]}),
feature("franchisee-audit-workbench","FRA12","Franchisee audit workbench","Reconcile franchisee audit workbench using franchise agreements, POS detail, aggregator sales, bank deposits, tax filings, GL data, exemptions, and remittances.","Produce a governed franchisee audit workbench decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["franchisee","Franchisee / Location","text","Harbor Foods #184"],["period","Royalty Period","text","2026-Q2"],["reportedAmount","Reported Royalty & Fund","currency",184000],["expectedAmount","Expected Royalty & Fund","currency",228500]],{amountField:"reportedAmount",subjects:["Quick-service restaurant","Fitness franchise","Home-services franchise","Hospitality franchise","Retail franchise"]}),
feature("finding-and-evidence-package","FRA13","Finding and evidence package","Reconcile finding and evidence package using franchise agreements, POS detail, aggregator sales, bank deposits, tax filings, GL data, exemptions, and remittances.","Produce a governed finding and evidence package decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["franchisee","Franchisee / Location","text","Harbor Foods #184"],["period","Royalty Period","text","2026-Q2"],["reportedAmount","Reported Royalty & Fund","currency",184000],["expectedAmount","Expected Royalty & Fund","currency",228500]],{amountField:"reportedAmount",subjects:["Quick-service restaurant","Fitness franchise","Home-services franchise","Hospitality franchise","Retail franchise"]}),
feature("response-and-collection-tracking","FRA14","Response and collection tracking","Reconcile response and collection tracking using franchise agreements, POS detail, aggregator sales, bank deposits, tax filings, GL data, exemptions, and remittances.","Produce a governed response and collection tracking decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["franchisee","Franchisee / Location","text","Harbor Foods #184"],["period","Royalty Period","text","2026-Q2"],["reportedAmount","Reported Royalty & Fund","currency",184000],["expectedAmount","Expected Royalty & Fund","currency",228500]],{amountField:"reportedAmount",subjects:["Quick-service restaurant","Fitness franchise","Home-services franchise","Hospitality franchise","Retail franchise"]}),
feature("systemwide-leakage-analytics","FRA15","Systemwide leakage analytics","Reconcile systemwide leakage analytics using franchise agreements, POS detail, aggregator sales, bank deposits, tax filings, GL data, exemptions, and remittances.","Produce a governed systemwide leakage analytics decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["franchisee","Franchisee / Location","text","Harbor Foods #184"],["period","Royalty Period","text","2026-Q2"],["reportedAmount","Reported Royalty & Fund","currency",184000],["expectedAmount","Expected Royalty & Fund","currency",228500]],{amountField:"reportedAmount",subjects:["Quick-service restaurant","Fitness franchise","Home-services franchise","Hospitality franchise","Retail franchise"]})
]);
